apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-kandidatsok-api
  namespace: toi
  labels:
    team: toi
azure:
  application:
    enabled: true
    allowAllUsers: false
    claims:
      extra:
        - NAVident
      groups:
        - id: c6524400-7cd1-4296-9009-410133690545
        - id: 964aaae2-cf18-486b-bead-f507ff3a50b2
spec:
  image: {{{image}}}
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand
