apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-kandidatsok-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{{image}}}
  ingresses:
  {{#each ingress as |url|}}
     - {{ url }}
  {{/each}}
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: {{adGruppeModiaGenerellTilgang}}
          - id: {{adGruppeModiaOppfolging}}
  openSearch:
    access: read
    instance: kandidat
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand
    outbound:
      external:
        - host: {{ pdlHost }}
        - host: {{ modiaContextHolderHost }}
  env:
    - name: MODIA_GENERELL_GRUPPE
      value: {{adGruppeModiaGenerellTilgang}}
    - name: MODIA_OPPFOLGING_GRUPPE
      value: {{adGruppeModiaOppfolging}}
    - name: PDL_URL
      value: {{pdlUrl}}
    - name: PDL_SCOPE
      value: {{pdlScope}}
    - name: MODIA_CONTEXT_HOLDER_URL
      value: {{modiaContextHolderUrl}}
    - name: MODIA_CONTEXT_HOLDER_SCOPE
      value: {{modiaContextHolderScope}}