name: Build, test and deploy
on: [push, workflow_dispatch]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - run: ./gradlew assemble

      - uses: nais/docker-build-push@v0
        id: docker
        with:
          team: toi
          tag: ${{ github.sha }}
          dockerfile: Dockerfile
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  deploy-to-dev:
    name: Deploy to dev
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    needs: build-test-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yaml
          VAR: image=${{ needs.build-test-deploy.steps.docker.outputs.image }}
          VARS: deploy/dev-gcp.json

  deploy-to-prod:
    name: Deploy to prod
    if: github.ref == 'refs/heads/main'
    needs: [build-test-deploy, deploy-to-dev]
    runs-on: ubuntu-latest
    steps:
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/nais.yaml
          VAR: image=${{ needs.build-test-deploy.steps.docker.outputs.image }}
          VARS: deploy/prod-gcp.json