name: Build and deploy
on: [ push, workflow_dispatch ]
jobs:
  call-build-and-publish:
    uses: ./.github/workflows/build-and-publish.yaml

  deploy-to-dev:
    name: Deploy to dev
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/trivy2'
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yaml
          VAR: image=${{ needs.build-and.publish.outputs.image }}
          VARS: nais/dev-gcp.json

  deploy-to-prod:
    name: Deploy to prod
    if: github.ref == 'refs/heads/main'
    needs: [ build-and-publish, deploy-to-dev ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/nais.yaml
          VAR: image=${{ needs.build-test-deploy.outputs.image }}
          VARS: nais/prod-gcp.json
